version: '3.7'

networks:
  c4cnet:


services:
  cpsv_ap:
    container_name: cpsv_ap
    build:
      context: .
    networks:
      c4cnet:
    ports:
      - "7650:80"
    volumes:
      - ".:/app"
    env_file:
      - secrets/cpsv_ap.env



