version: '3.7'

networks:
  c4cnet:


services:
  cpsv_ap:
    container_name: cpsv_ap_python
    build:
      context: .
      args:
        - GIT_TOKEN=$GIT_TOKEN
    networks:
      c4cnet:
    ports:
      - "7650:80"
    volumes:
      - ".:/app"
    env_file:
      - secrets/cpsv_ap.env
    environment:
      - URL_ORION=http://orion:1026

  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - c4cnet
    command: --nojournal

  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - c4cnet
    ports:
      - "1026:1026"
    #    command: -dbhost mongo-db
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  bert_classifier_train:
    build:
      context: ./src/BERT_classifier
      args:
        - MODEL_DIR=MODELS/model_MULTI_BERT_unfreeze_last_layers_5epoch_C4C_translations
    networks:
      c4cnet:
    volumes:
      - ".:/work"

  relations_classifier_bert_api_cpu:
    build:
      context: ./src/BERT_classifier
      dockerfile: ./app/Dockerfile
      args:
        - MODEL_DIR=MODELS/model_MULTI_BERT_unfreeze_last_layers_5epoch_C4C_translations
    ports:
      - "5000:5000"
    volumes:
      - ".:/train"
