version: '3.7'

networks:
  c4cnet:


services:
  cpsv_ap:
    container_name: cpsv_ap_python
    build:
      context: .
      args:
        - GIT_TOKEN=$GIT_TOKEN
    networks:
      c4cnet:
    ports:
      - "7650:80"
    volumes:
      - "./c4c_cpsv_ap:/app/c4c_cpsv_ap"
      - "./connectors:/app/connectors"
      - "./context_broker:/app/context_broker"
      - "./data:/app/data"
      - "./relation_extraction:/app/relation_extraction"
      - "./scripts:/app/scripts"
      - "./src/BERT_classifier:/app/BERT_classifier"
    env_file:
      - secrets/cpsv_ap.env
    environment:
      - URL_ORION=http://orion:1026
    depends_on:
      - relations_classifier_bert_api_cpu
      - title_classifier

  mongo-db:
    image: mongo:4.4
    hostname: mongo-db
    container_name: db-mongo
    expose:
      - "27017"
    ports:
      - "27017:27017"
    networks:
      - c4cnet
    command: --nojournal

  orion:
    image: fiware/orion-ld
    hostname: orion
    container_name: fiware-orion
    depends_on:
      - mongo-db
    networks:
      - c4cnet
    ports:
      - "1026:1026"
    #    command: -dbhost mongo-db
    command: -dbhost mongo-db -logLevel DEBUG
    healthcheck:
      test: curl --fail -s http://orion:1026/version || exit 1

  bert_classifier_train:
    build:
      context: ./src/BERT_classifier
    networks:
      c4cnet:
    volumes:
      - ".:/work"

  relations_classifier_bert_api_cpu:
    build:
      context: ./src/BERT_classifier
      dockerfile: app/Dockerfile
      args:
        - MODEL_DIR=MODELS/epoch_35_Mon_Mar_21_142602_2022_d5fa026ea92211ec98150242ac120002
    command: uvicorn BERT_classifier.app.main:app --host 0.0.0.0 --port 5000
    ports:
      - "7690:5000"
    volumes:
      - "./src/BERT_classifier:/work/BERT_classifier"
    networks:
      c4cnet:

  title_classifier:
    build:
      context: ./src/BERT_classifier
      dockerfile: app/Dockerfile
      args:
        - MODEL_DIR=MODELS/title_classifier_epoch_39_Sat_Apr_9_05u50m40s_2022
    command: uvicorn BERT_classifier.app.main:app --host 0.0.0.0 --port 5000
    ports:
      - "7692:5000"
    volumes:
      - "./src/BERT_classifier:/work/BERT_classifier"
    networks:
      c4cnet:

  fuseki:
    # In ro-rdf API set endpoint to http://fuseki:3030/<dataset>
    # in order to connect to this dataset
    container_name: fuseki
    build:
      context: ./fuseki
    #    image: stain/jena-fuseki
    # Fix database problem (https://github.com/stain/jena-docker/issues/34#issuecomment-846905725)
    ports:
      - 7630:3030
    volumes:
      - fuseki-data:/fuseki
    environment:
      - ADMIN_PASSWORD=$FUSEKI_PASS
      - FUSEKI_BASE=/fuseki
      - JVM_ARGS=-Xmx3g
      - FUSEKI_DATASET_1=CEFAT4Cities # Creates empty dataset
    networks:
      - c4cnet

    depends_on:
      - fuseki-data

  fuseki-data:
    image: busybox
    volumes:
      - /fuseki #<container_name>:<mount_point>

volumes:
  fuseki-data:
